name: 💬 Auto Comment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]

jobs:
  auto_comment:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 Auto Comment on Issues and PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            const author = context.payload.sender.login;
            
            if (context.eventName === 'issues' && context.payload.action === 'opened') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: `👋 Hi @${author},

                Issues are only for reporting bugs or feature requests. Please read the documentation before raising an issue: https://rengine.wiki

                Please include all the requested and relevant information when opening a bug report. Improper reports will be closed without any response.`
              });
            } else if (context.eventName === 'pull_request' && context.payload.action === 'opened') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: `👋 Hi @${author},

                Thank you for sending this pull request.

                Please make sure you have followed our [contribution guidelines](https://github.com/yogeshojha/rengine/blob/master/.github/CONTRIBUTING.md).

                We will review this PR as soon as possible. Thank you for your patience.`
              });
            } else if (context.eventName === 'pull_request' && context.payload.action === 'closed') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: `🚀 Hi @${author},

                You are amazing! Thank you for your contributions. Your contributions are what makes reNgine awesome!

                This pull request has now been closed.

                We look forward to your future contributions and support.

                Thanks`
              });
            }