name: 🚀 Release

on:
  push:
    branches:
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@v4

      - name: Generate Release Notes
        id: generate-notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false